server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE}:8002/eureka/
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: balance-service-a
        uri: lb://balance-service-a
        predicates:
        - Path=/savings/a/**
        filters:
        - RewritePath=/savings/a/(?<path>.*), /$\{path}
      - id: balance-service-b
        uri: lb://balance-service-b
        predicates:
          - Path=/savings/b/**
        filters:
          - RewritePath=/savings/b/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: balance
        url: /v3/api-docs/balance