server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOST}:${RDS_PORT}/${RDS_DBNAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE}:8002/eureka/

springdoc:
  packagesToScan: com.kadmos.services.balance
